name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Install
        run: ./install.sh
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v2